# Generated by Django 4.2.1 on 2023-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.IntegerField(max_length=20)),
                ('background', models.TextField()),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
    ]
